version: '3.8'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
    depends_on:
      - tor-socks
    networks:
      kuma:
        ipv4_address: 172.19.0.2
  tor-socks:
    #Credits; https://github.com/reverse-hash/bitcoin-full-node-with-docker/blob/main/tor/Dockerfile
    image: tor:0.4.7.13
    build:
      context: ./tor
      args:
        - TOR_VERSION=0.4.7.13
        - GROUP_ID=1000
    restart: unless-stopped
    volumes:
      - ./tor/torrc.default:/home/tor/torrc.default
    networks:
      kuma:
        ipv4_address: 172.19.0.3
volumes:
  uptime-kuma:
networks:
  kuma:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1