version: '3.8'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: always
    ports:
    - 3001:3001
    volumes:
    - uptime-kuma:/app/data
    depends_on:
      - tor-socks
    networks:
      default:
        ipv4_address: 172.18.0.2
  tor-socks:
    #Credits; https://github.com/reverse-hash/bitcoin-full-node-with-docker/blob/main/tor/Dockerfile
    image: tor:12.0.4
    build:
      context: ./tor
      args:
        - TOR_VERSION=12.0.4
        - TOR_PLATFORM=linux-x86_64
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.3
volumes:
  uptime-kuma:
  tor:
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1